---
title: "Diet analysis of herring predation in Puget Sound"
output: html_notebook
---


Load libraries
```{r load libraries, include=FALSE}
source("libraries.R")
source("test_herring.R")
source("test_herring_raw_data.R")
source("clean_herringdata.R")
source("make_map.R")
source("get_basin_coord.R")
source("get_raw_data.R")
```


Check full diet data set for herring prey and move to herring diet folder, add full reference

```{r check data, include=FALSE}

data.files <- list.files(path="~/herringdiet/all_diet_data",pattern = "*.xlsx", full.names = TRUE)

#Moves data files to herring data
lapply(data.files,test_herring)

data.files.raw <- list.files(path="~/herringdiet/raw_diet_data",pattern = "*.csv", full.names = TRUE)

#Moves data files to herring data
lapply(data.files.raw,test_herring_raw_data)


```


Include raw herring data

```{r}
# add raw data clean files

#source("Kwiath_diets.R")
#source("clean_raw_data.R")

raw.data.files <- list.files("~/herringdiet/raw_diet_data_rev", full.names = TRUE)

raw.data <- lapply(raw.data.files,get_raw_data) %>% 
  bind_rows %>% 
   dplyr::select(-loc_date_index, -num_fish, -taxa_predator, -loc_index) %>% 
  rename(predator_taxa = predator)

raw.data %>% 
  write_csv("~/herringdiet/herring_raw_diet_data.csv")
```



```{r clean herring data}


raw.data  <- fread("herring_raw_diet_data.csv") %>% 
  as_tibble

data.folder <- "~/herringdiet/herring_data_rev"

data.files <- list.files(path=data.folder,pattern = "*.xlsx", full.names = TRUE)

herring.clean.data <- lapply(data.files, clean_herringdata, diet.names="diet_file_list.csv", predator.list = "herring_predator_names.csv") %>% 
  bind_rows

all.herring.data <- herring.clean.data %>% 
   dplyr::select(-file_name, -full_file_name, -data, -index, -value, -predator_name) %>% 
  bind_rows(raw.data)

diet.file.names <- read_csv("diet_file_list.csv") %>% 
  rename(file_name = FILE, reference = CITA)

herring.clean.data %>% 
  mutate(file_name=gsub(".xlsx","",file_name)) %>% 
  left_join(diet.file.names, by="file_name") %>% 
  distinct(file_name, reference) %>% 
  arrange(reference) %>% 
  #filter(is.na(reference)) %>% 
  write_csv("herring_references.csv")

  #using all predators
  #selected groups are 
  #pred.groups <- c("HSL","PIN","SAL","SB","FMM","CI","CO","CU","DOG","PIS","ROC","MRO","SMD","SP")
  
  
all.herring.data %>% 
  #filter(is.na(latitude) & !is.na(longitude)) %>% 
  distinct(location, latitude,longitude) %>% 
  arrange(location) %>% 
  write_csv("herring_locations.csv")

#join with Raw data and convert predator_size based on units


clean.all.herring.data <- all.herring.data %>% 
   mutate(predator_stage = if_else(predator_stage=="juvenileAndadult","adult",predator_stage)) %>% 
  mutate(atlantis_pred_group = if_else(atlantis_pred_group == "STEELHEAD", "ST", atlantis_pred_group)) %>% 
  mutate(predator_size=if_else(size_units=="in",predator_size*25.4,
                               if_else(size_units=="cm",predator_size*10,
                                       if_else(size_units=="lbs",predator_size*453.592,predator_size)))) %>% 
  mutate(size_units=if_else(size_units=="lbs","g",
                            if_else(size_units=="cm","mm",
                                    if_else(size_units=="in","mm", size_units)))) %>% 
  mutate(size_units = if_else(size_units=="NA",NA_character_,size_units)) %>% 
  mutate(predator_size = if_else(atlantis_pred_group=="HSL" & size_units=="g",(((predator_size/1000)*5095)^(1/2.550)),predator_size)) %>% 
  mutate(size_units = if_else(atlantis_pred_group=="HSL" & size_units=="g","mm",size_units)) #%>% 
 # filter(proportion>0)
#used relationship for HSL lenght from Boulva & McLaren 1979 , W(kg) = L(cm)^2.550/5695

clean.all.herring.data %>% 
  write_csv("herring_diet_data.csv")



```


Plot sampling points and map

```{r make map, echo=FALSE}

 #https://boundingbox.klokantech.com/
#-123.7904,47.0152,-121.9301,49.2511 Puget Sound

shape.file <- "USMaritimeLimitsNBoundaries.shp"
boundary.file <- "shapefile_4071.shp"
file.name <- "herring_map.png"
scale.factor <- 2 #map scale
bar.position  <- "tl" #position scale bar
max.long <- -121.9
min.long <- -125
min.lat <- 46
max.lat <- 50
herring.locations <-"herring_diet_data.csv"

make_map(shape.file, boundary.file, file.name, scale.factor, bar.position, max.long, min.long, min.lat, max.lat, herring.locations)

```


Assign each data point to a basin

```{r assign basin, echo=TRUE}

herring.locations <-"herring_diet_data.csv"
boundary.file <- "shapefile_4071.shp"


herring.basin.data <- get_basin_coord(herring.locations, boundary.file)

write_csv(herring.basin.data, "herring_diet_basin_data.csv")

```


Summarize number of samples by categories
```{r}

herring.data <- read_csv("herring_diet_basin_data.csv")


year.data <- herring.data %>% 
  mutate(index_rows = 1) %>% 
  group_by(atlantis_pred_group, year) %>%
  summarize(tot_data = sum(index_rows))


basin.data <- herring.data %>% 
  mutate(index_rows = 1) %>% 
  group_by(atlantis_pred_group, predator_stage, basin) %>%
  summarize(tot_data = sum(index_rows))

ps.data <- herring.data %>% 
  mutate(index_rows = 1) %>% 
  group_by(atlantis_pred_group, predator_stage) %>%
  summarize(tot_data = sum(index_rows))

herring.data %>% 
  distinct(atlantis_pred_group, predator_taxa) %>% 
  arrange(atlantis_pred_group, predator_taxa)

red.pal1 <- redmonder.pal(8,"qMSOBuWarm")[c(2,1)]

sample.plot <- basin.data %>% 
      ggplot(aes(x=atlantis_pred_group, y=tot_data, fill = predator_stage)) + 
      geom_col()+
      scale_fill_manual(values=red.pal1, name = "Predator stage")+
      theme_classic()+
      theme(legend.position = "bottom")+
      ylab("Data samples") + 
      xlab("Predator group")
 
red.pal2 <-  c(redmonder.pal(8,"qMSOMed"),redmonder.pal(8,"qMSOPap")[8])

basin.plot <- basin.data %>% 
      ggplot(aes(x=atlantis_pred_group, y=tot_data, fill = basin)) + 
      geom_col()+
      scale_fill_manual(values=red.pal2, name = "Basin")+
      theme_classic()+
      theme(legend.position = "bottom")+
      ylab("Data samples") + 
      xlab("Predator group") 

grid.sample <- grid.arrange(sample.plot, basin.plot, ncol=1)

ggsave("herring_samples_plot.png", grid.sample, device="png",width=10,height=10, dpi=350)

   
year.plot <- year.data %>% 
      ggplot(aes(x=year, y=tot_data, group = atlantis_pred_group)) + 
      geom_point(size=1, color = "steelblue4")+
  geom_line(color = "steelblue2")+
  facet_wrap(~ atlantis_pred_group)+
     # scale_fill_manual(values=red.pal2, name = "Basin")+
      theme_classic()+
      ylab("Data samples") + 
      xlab("Year") 
   
ggsave("herring_year_plot.png", year.plot, device="png",width=9,height = 7,dpi=350)
    


  
```


Fit model
```{r}

#used http://jacolienvanrij.com/Tutorials/GAMM.html
#https://fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/

herring.basin.data <- read_csv("herring_diet_basin_data.csv")

herring.basin.data.scaled <- herring.basin.data %>% 
  mutate(proportion_sc=(0.999*(0.00001+proportion)))
#beta distribution does not use 0 or 1 values
#Ainsworth et al used this approach to scale the diet proportion values
#dat2 <- cbind(x[,1:2],(0.999*(0.00001 + x[,3:(nprey+2)]/rowSums(x[,3:(nprey+2)]))))


herring.spawning <- read_csv("herring_spawning_numbers.csv")

herring.data.spawning <- herring.basin.data.scaled %>% 
  left_join(herring.spawning, by = "year")

ps.basins <- herring.data.spawning %>% 
  distinct(basin) %>% 
  arrange(basin) %>% 
  mutate(basin_id=1:nrow(.))

pred.stages <- herring.data.spawning %>% 
  distinct(predator_stage) %>% 
  arrange(predator_stage) %>% 
  mutate(predator_stage_id=1:nrow(.))

pred.groups <- herring.data.spawning %>% 
  distinct(atlantis_pred_group) %>% 
  arrange(atlantis_pred_group) %>% 
  mutate(atlantis_pred_group_id=1:nrow(.))

herring.basin.data.mod <- herring.data.spawning %>% 
  left_join(ps.basins, by="basin") %>% 
  left_join(pred.stages, by="predator_stage") %>% 
  left_join(pred.groups, by="atlantis_pred_group")

# examine data

fit.norm <- fitdist(herring.basin.data.mod$proportion_sc, distr = "beta", method = "mme")
plot(fit.norm)

est_kvalue <- function(eachkvalue){
  
  print(eachkvalue)
  herring.m2 <- gam(proportion_sc ~ s(year, bs="ts") + s(longitude,latitude, bs="ts", k = eachkvalue), family=betar(link="logit"), data=herring.basin.data.mod)

  aic.value <- AIC(herring.m2)
  print(aic.value)
  
  result.frame <- tibble(k_value=eachkvalue,AIC=aic.value)
  return(result.frame)
}

kvalues <- seq(10,100, by=1)

kvalues.table <- lapply(kvalues,est_kvalue) %>% 
  bind_rows

#models

#Gamma log link can only be used if there are non-zero values
herring.m1 <- gam(proportion_sc ~ s(year, bs="cr") + s(longitude,latitude, bs="ts", k = 10), family=betar(link="logit"),data=herring.basin.data.mod)

herring.m2 <- gam(proportion_sc ~ s(year, bs="ts") + s(longitude,latitude, bs="ts", k = 10), family=betar(link="logit"), data=herring.basin.data.mod)

herring.m3 <- gam(proportion_sc ~ s(year, bs="cr") + s(all_herring, bs="cr") + s(longitude,latitude, bs="ts", k = 10), family=betar(link="logit"), data=herring.basin.data.mod)

herring.m4 <- gam(proportion_sc ~ s(year, bs="ts") + s(all_herring, bs="ts") + s(longitude,latitude, bs="ts", k = 10), family=betar(link="logit"), data=herring.basin.data.mod)

herring.m5 <- gam(proportion_sc ~ s(year, bs="tp") + s(all_herring, bs="tp") + s(longitude,latitude, bs="tp", k = 10), family=betar(link="logit"), data=herring.basin.data.mod)

herring.m6 <- gam(proportion_sc ~ s(year, bs="ts") + s(all_herring, bs="ts") + s(longitude,latitude, bs="ts", k = 10) + s(predator_size, bs="ts"), family=betar(link="logit"), data=herring.basin.data.mod)

#te terms produce smooths of multiple predictors from tensor productos of any bases available for use with s
#higher k can result in very complicated shapes, better to leave the default
herring.m7 <- gam(proportion_sc ~ te(year, bs="ts") + s(all_herring, bs="ts") + s(longitude,latitude, bs="ts", k = 10) + s(predator_size, bs="ts"), family=betar(link="logit"), data=herring.basin.data.mod)

# The m= argument allows one to specify different types of covariance functions.
#this model separates herring by stock
herring.m8 <- gam(proportion_sc ~ s(longitude,latitude, bs="ts", k = 10, m=2)+ te(year, bs="ts")+ s(cherry_point, bs="ts") +  s(other_herring, bs="ts") + s(predator_size, bs="ts"), family=betar(link="logit"),
                  data=herring.basin.data.mod)

#include basin as a random term
herring.m9 <- gam(proportion_sc ~ s(longitude,latitude, bs="tp", k = 10)+ te(year)+ s(cherry_point, bs="ts") +  s(other_herring, bs="ts") +  s(predator_size, bs="tp") + s(basin_id, bs = 're'), family=betar(link="logit"),
                  data=herring.basin.data.mod)

#add predator stage as a smoother
herring.m10 <- gam(proportion_sc ~ s(longitude,latitude, bs="tp", k = 10)+ te(year)+ s(cherry_point, bs="ts") +  s(other_herring, bs="ts") +  s(predator_size, bs="tp") + s(basin_id, bs = 're') + s(predator_stage_id, bs = 're'), family=betar(link="logit"),
                  data=herring.basin.data.mod)


#add predator stage as a smoother
herring.m11 <- gam(proportion_sc ~ s(longitude,latitude, bs="tp", k = 10)+ te(year)+ s(atlantis_pred_group_id, bs="ts")+ s(cherry_point, bs="ts") +  s(other_herring, bs="ts") +  s(predator_size, bs="tp") + s(basin_id, bs = 're') + s(predator_stage_id, bs = 're'), family=betar(link="logit"),
                  data=herring.basin.data.mod)


AIC.summary <- c(AIC(herring.m1),AIC(herring.m2),AIC(herring.m3),AIC(herring.m4),AIC(herring.m5),AIC(herring.m6),AIC(herring.m7),
  AIC(herring.m8),AIC(herring.m9),AIC(herring.m10),AIC(herring.m11)) %>% 
  as_tibble %>% 
  mutate(model=1:11) %>% 
  arrange(desc(value))

write_csv(AIC.summary, "AIC_model_summary.csv")

plot(herring.m1, residuals=TRUE)

#this plot omits parts of the smooths that are to far from covariate values
plot(herring.m2, too.far = 0.15)

gam.check(herring.m1)


#compute semivariogram

data.coords <- herring.basin.data.mod %>% 
  dplyr::select(longitude, latitude) %>% 
  as.matrix()

res.data <- residuals(herring.m1) %>% 
  as.matrix()

variog.data <- variog(coords=data.coords,data=res.data)

plot(variog.data)

acf(herring.basin.data.mod$year)



```


Only include predator groups with more than 50 data points
```{r}
#used http://jacolienvanrij.com/Tutorials/GAMM.html
#https://fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/

herring.basin.data <- read_csv("herring_diet_basin_data.csv")

ps.data <- herring.basin.data %>% 
  mutate(index_rows = 1) %>% 
  group_by(atlantis_pred_group) %>%
  summarize(tot_data = sum(index_rows)) %>% 
  filter(tot_data>50) %>% 
  distinct(atlantis_pred_group) %>% 
  pull(atlantis_pred_group)

herring.pred.data <- herring.basin.data %>% 
  filter(atlantis_pred_group %in% ps.data)

herring.spawning <- read_csv("herring_spawning_numbers.csv")

herring.data.spawning <- herring.pred.data %>% 
  left_join(herring.spawning, by = "year")

herring.basin.data.mod <- herring.data.spawning %>% 
  mutate(predator_stage = as.factor(predator_stage)) %>% 
   mutate(atlantis_pred_group = as.factor(atlantis_pred_group)) %>% 
  mutate(sample_source = as.factor(sample_source)) %>% 
  mutate(variable = as.factor(variable)) %>% 
  mutate(basin = as.factor(basin))


#with factor include intercept difference: Group + s(Time, by=Group).

#with ordered factor include intercept difference and reference smooth: Group + s(Time) + s(Time, by=Group).

#with binary predictor include reference smooth: s(Time) + s(Time, by=IsGroupChildren).
#m2 <- gam(value + basin ~ s(year), data=herring.basin.data)


gam.model <- gam(proportion ~ year +
                   s(year, by=basin) +
                   s(proportion, by=atlantis_pred_group) +
                   s(year, atlantis_pred_group, bs='fs', m=1)+
                   s(all_herring, basin, bs = "fs", m=1),
                   data = herring.basin.data.mod,
                   rho=valRho)


#random smooths adjust the trend of a numeric predictor in a nonlinear way: s(Time, Subject, bs="fs", m=1).


#check the distribution and autocorrelation structure of the residuals:

check_resid(gam.model, split_by=c("year", "atlantis_pred_group"))

summary(gam.model)

save(gam.model, file="gam_model_herring.rda", compress='xz')

# set two plot panels:
par(mfrow=c(1,2), cex=1.1)

# Plot difference surface:
plot_diff2(gam.model, view=c("year", "predator-stage"), 
    comp=list(Group=c("adults", "juveniles")), 
    plotCI=TRUE, rm.ranef=TRUE,
    main="Adults-Juveniles",
    zlim=c(-13,13))

```



Extra code
```{r}
#used geocoding to get locations, but ended up going through each article to find the maps and find the corresponding coordinates
# revised data files are in herring_data_rev

# location.table <- lapply(sampling.locations,get_location) %>% 
#   bind_rows
# 
# write_csv(location.table,"sampling_coordinates.csv")
# # I reviewed this manually for missing data, and saved as "sampling_coordinates_rev.csv"
# 
# location.data <- read_csv("sampling_coordinates_rev.csv")
# 
# herring.loc.corr <- herring.clean.data %>% 
#   filter(latitude==0) %>% 
#   dplyr::select(-latitude,-longitude) %>% 
#   left_join(location.data,by="location")
# 
# herring.loc.data <- herring.clean.data %>% 
#   filter(!latitude==0) %>% 
#   bind_rows(herring.loc.corr)
```

